#!/bin/bash
environ=$1
# 当前目录地址
dir=`pwd`
# 目录名
dirName=`basename $dir`
# 上一级目录地址
preDir=${PWD%/*}
# 上一级构建目录地址
preBuild="${preDir}/${dirName}-build"
# 本机ip
# osascript -e "IPv4 address of (system info)"  (mac系统)
ipStr=`ifconfig en0 |grep "inet " |awk '{print $2}'`
openUrl=http://${ipStr}:3000

# 如果构建目录不存在就创建一个
if [ ! -d "$preBuild" ]; then
  mkdir $preBuild
fi
rm -rf ${preBuild}/*

fis3 server start --type smarty --no-browse --root $preBuild
open $openUrl
nohup browser-sync start --proxy "${ipStr}:8080" --no-open --files * --reload-delay 1000 &
fis3 release ${environ:-debug} -wc
